### PR TITLE
fix: catch FileSystem.fetch network offline error

### PR DESCRIPTION
**Pull request by youniaogu**
if `FileSystem.fetch` meet network error（e.g. phone get weak signal when inside metro）, it with throw error instead of return response

how to repoduct: prefetch multiple image, switch network to offline, switch to online after wait a moment, re prefetch always return error `Failed to fetch 'url'. The Internet connection appears to be offline.`

### CODE REVIEW

**Comment by youniaogu** [comment]
it looks good to me

but i think handle image not found is unnecessary, because it already handle by the result with code 404

```javascript
// image not found already handle by here
if (result && result.status !== 200) {
  this.downloadPromise = undefined;
  return undefined;
}
```

should i push you code snippet to commit?

**Comment by efstathiosntonas** [comment]
@youniaogu we need to check for 404 on the retry function otherwise we will send 3 requests, 404 should stop the retry function, I believe we should move this:

``tsx
if (result && result.status !== 200) {
  this.downloadPromise = undefined;
  return undefined;
} 
``` 
in the retry error. 

I'll run some tests and then I'll commit the retry logic.

**Comment by youniaogu** [comment]
@efstathiosntonas thank you, it help me so much

**Comment by efstathiosntonas** [comment]
@youniaogu released [2.9.0](https://github.com/georstat/react-native-image-cache/releases/tag/v2.9.0), i've also added the retry logic. Thank you.

**Pull request merged**
