### PR TITLE
update cached image with fastimage, webp, mmkv

### PR DESCRIPTION
**Pull request by computerjazz**
Hi! Here are the changes we chatted about on reddit. I'm sure there's been some drift between your package and the time that we forked it, but I hope this is somewhat useful! 

- We noticed lots of jank when scrolling a large list of images, so we swapped out RN's image component for FastImage here, which fixed it . We blow away the FastImage cache on each launch, because we don't actually want FastImage doing any caching. It'd be cool if there was some bare bones SDImage/Glide package that was more of an unopinionated pass-through, but this works for us.

- We had to patch in webp support for the default case here (it appears that the jpg extension causes issues when the image is actually webp)

- We wanted to periodically download fresh images swr-style

- We persist the resolved uri with MMKV so it's available immediately on mount and doesn't have to go through a load cycle (also required more error handling for when iOS has cleared out the cache dir behind the scenes). Note I didn't actually add mmkv to this PR, but added a `usePersistedState` stub instead.

- We split the components into an animated/non-animated versions so we don't pay the reanimated performance price on non-animated images.

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
perfect, thank you @computerjazz !!

**Comment by efstathiosntonas** [comment]
@computerjazz just a side note, be careful with `useStableCallback` and `Suspense` (if you use it in your apps) it can lead to weird side effects, haven't tested it myself, I've seen people talking about it here and there. 

ps. great job on react-native-draggable-flatlist

**Comment by computerjazz** [comment]
thanks!

Do you have any links for that stable callback + suspense issue? I use it literally everywhere haha -- super useful for cases where you just want to call a function with the freshest available state.

**Comment by efstathiosntonas** [comment]
@computerjazz https://reddit.com/r/reactjs/s/wi5NCGqHsd

**Comment by DenisQC** [comment]
I see this PR is still draft but I'm wondering, is it meant to support `FastImage` for in-memory cache while `react-native-image-cache` does in-disk stored cache? 🤔

**Comment by efstathiosntonas** [comment]
Hi @DenisQC, this PR will not be merged, me and @computerjazz had a discussion on reddit and he posted his tweaks/changes as a PR so we can see the diff.

**Comment by computerjazz** [comment]
Closed to prevent confusion

**Pull request closed without merging**
